spring:
    datasource:
        url: jdbc:postgresql://localhost:3308/blogwithmicroservice
        username: postgres
        password: root123
        

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
